### ISSUE TITLE
CLA bot rejecting GitHub noreply email

### ISSUE THREAD

**Issue by thejamesm** [edgedb/cla-bot#57]
I'm trying to make a (very simple) pull request to cpython, but the CLA bot isn't recognising me as its author:

`Thank you for authorizing our application, but the CLA must be signed by the users who contributed to the PR. Authors emails are: 1981099+thejamesm@users.noreply.github.com.`

There's a similar issue at [edgedb/cla-bot#50](https://github.com/edgedb/cla-bot/issues/50), but the conclusion there was that it came down to case sensitivity, which I don't believe to be the case here.

Am I not able to contribute without exposing my real email address? How can I resolve this?

**Comment by thejamesm** [comment]
The issue seems to have resolved itself. No idea how, but glad it's now working.

**Comment by thomas-2nd** [comment]
Hi, how did you manage to create a Google account with the noreply email? I understand that it is needed for the CLA. 

My address is getting rejected.

**Comment by thejamesm** [comment]
> Hi, how did you manage to create a Google account with the noreply email? I understand that it is needed for the CLA.
> 
> My address is getting rejected.

I'm sorry, to my recollection I didn't create a new Google account or anything like that. Like I said in [my comment above](#issuecomment-2114943954), as far as I could tell the issue just seemed to fix itself. I know that isn't very helpful, but it's all I can offer.
